### ISSUE TITLE
Virtual Proxy Without Windows Authentication

### ISSUE THREAD

**Issue by KeremPekcabuk** [stefanwalther/sense-export#3]
It seems the extension always creates the link like https://servername/tempcontent/.....xlsx. When using windows authentication this is not a problem because virtual proxies authenticate users automatically. But when using ticket authentication other then windows users, the export link must be https://servername/virtualproxyname/tempconten/....xlsx instead https://servername/tempcontent/.....xlsx. This is the only issue for this extension.

**Comment by stefanwalther** [comment]
Thx for reporting, I'll investigate.

**Comment by Chenjie** [comment]
Hi, any fix for this yet? 
having same problem using the extension, it redirect without include the Virtual proxy. and the content is not found, after add /virtualproxyname/ to the url, it's work.

**Comment by stefanwalther** [comment]
The evil is definitely here: https://github.com/stefanwalther/sense-export/blob/master/src/swr-sense-export.js#L20

I'll think of a better way how to deal with that, will try to get a fix uploaded ASAP.

**Comment by katewologun** [comment]
Hi has anyone found an fix or workaround to include the virtual proxy?

**Comment by KeremPekcabuk** [comment]
Not yet it seems :)

**Comment by henriqueantunes** [comment]
After spending some time trying to understand why this was going on i gave up and did a little modification on the swr-sense-export.js. 

`				$scope.export = function() {

					var exportOpts = {
						format: $scope.layout.props.exportFormat,
						state: $scope.layout.props.exportState,
						filename: $scope.layout.props.exportFileName,
						download: false
					};
					
					var config = {
						prefix: "/admin/"
					}
					
					if ( qlik.table ) {
						var qTable = qlik.table( this );
						qTable.exportData( exportOpts, function( result ) {
							console.log( result );
							window.open(result.substring(3));
						} ); //Todo: this will open the link using window.open, so popup-blockers might catch that
					} else {
						//console.log('this', this.$parent.$parent.$parent.model);
						//this.$parent.$parent.$parent.model.session("ExportData",null, exportOpts.format, null, exportOpts.fileName, exportOpts.state);
					}

				}`

what you do is set the download to **false** and after the callback function you remove the "../" from the result url. Then your download will get the correct path if you are using a virtual proxy. Its not a solution but a little trick if you guys need to get this going asap just like me.

Regards.

**Comment by stefanwalther** [comment]
I have fixed this in the recent release v1.2.2, please give it a try.

Closing this issue, pls feel to re-open if this doesn't work for you.

**Comment by Kumikameli** [comment]
Hi Stefan

Thank you for very good extensions and contributions.

I just installed latest version (1.3.5) of the Sense-Export and the virtual proxy problem is still there. The download link is always in the format "https://servername/tempcontent/.....xlsx" even if the user is using the app via QS virtual proxy.

**Just to elaborate our environment/use case:**

The end user uses published apps via single sign-on and QS virtual proxy. The app URL is like this:
"https://servername/**proxyname**/single/?appid=xxxxxx&sheet=xxxxyyy".

When the user clicks the "Export"-button in the app, the browser will redirect to 
"https://servername/tempcontent/xxxxxxxxxx/somefilename.xlsx?serverNodeId=xxxxxx" and that will result to an error saying "The requested resource cannot be found."

If I manually put the proxy name to the URL, the exported file is downloaded fine:
"https://servername/**proxyname**/tempcontent/xxxxxxxxxx/somefilename.xlsx?serverNodeId=xxxxxx".


If there is no general solution easily available, is it possible to hard code the proxy name somewhere in the code? In our use that would be enough to solve all problems.

Thank you and best regards
